### ISSUE TITLE
Evolved Enderman strange behaviour after being hit by Ignition: Foundry Revolver

### ISSUE THREAD

**Issue by joselitosn** [p455w0rd/EndermanEvolution#10]
When shooting an Evolved Enderman with the Revolver from Ignition: Foundry, the EvoEnderman completely stops and soon all the mobs animations starts to get "jerky". Either they don't move at all or looks like they are teleporting (moving animations don't work). Also items and XP can't be collected from the ground.

Killing the EvoEnderman doesn't solve the problem, you have to exit and enter the save again. The same doesn't happen with any other mob added.

Minecraft 1.12.2 - Single Player
Forge 14.23.2.2617
Enderman Evolution 1.0.8
[Ignition: Foundry 3.1.1.0](https://github.com/Shadows-of-Fire/Foundry/blob/1.12.2/src/main/java/exter/foundry/item/firearm/ItemFirearm.java)

**Comment by p455w0rd** [comment]
can u get me some logs?

**Comment by joselitosn** [comment]
I can get them but i didn't see anything specific in them, since there are no crash logs either.

https://pastebin.com/3W0bYD02

**Comment by p455w0rd** [comment]
you reproduced what you are talking about in the instance that this log is from?

**Comment by joselitosn** [comment]
Yes, I made this specific instance with just these two mods (and it's dependencies) to make sure no other mods were interfering. On line 124 you can see the mods loaded.

**Comment by p455w0rd** [comment]
yeah i was just wanting to be sure that you shot one of my evolved enderman during this time to make sure it would print anything related to logs if there was anything..thanks for the report and working with me..i'll look into this first thing in the morning

**Comment by joselitosn** [comment]
Thanks, it worked in the latest version 1.0.9.

There is only a small problem. I'm not sure if it is intended, but i can't damage the EvoEnderman with normal bullets (that have no effects). If I use a bullet with Poison or Incendiary effects, only the effect of the bullet is applied. Frienderman just teleport away without receiving any damage or effect.

I tested with normal Enderman and I still can damage them.

**Comment by p455w0rd** [comment]
yup..this is intended..if you try hitting a vanilla Enderman with a shuriken from Tinkers or an arrow from a bow & arrow, you'll notice they TP before being able to be hit...well the bullets aren't real projectiles..they use hitScan logic, but in theory they're still projectiles...so I just replicated vanilla projectile functionality...for this reason you actually are able to hit vanilla Enderman with bullets
