### ISSUE TITLE
Frienderman cancels right click action

### ISSUE THREAD

**Issue by joselitosn** [p455w0rd/EndermanEvolution#11]
If I have an item in my hand which has a right click action (like drinking a potion), I can't execute the action while close and looking at the Frienderman.

Minecraft 1.12.2 - Single Player
Forge 14.23.2.2617
Enderman Evolution 1.0.9

**Comment by p455w0rd** [comment]
hmm..how are you finding these bugs XD...i think I know what's going on here..i'll look into it..but it'll be prolly a week before i do another update...releasing updates in too fast a succession is bad for pack authors and just creates more work for ppl at Curse...it's not game break..just don't target them when drinking and you'll be fine until the next update..thanks for posting

**Comment by joselitosn** [comment]
Well, I'm playing the mod. 😁 
And I also have another bug on the list. 🤣

They are small bugs and don't affect gameplay too much, so if I need a fix I can compile myself later.
