### ISSUE TITLE
Evolved Enderman causing overlay effect on items

### ISSUE THREAD

**Issue by joselitosn** [p455w0rd/EndermanEvolution#12]
If you look at one EvoEnderman while items or XP orbs are around, these items and orbs overlay become opaque. It can be better seen on the screenshot.

https://imgur.com/X2LBMqz

I like the current EvoEnderman effect, if to fix it you might have to change it, then I would prefer to keep it as it is.

Minecraft 1.12.2 - Single Player
Forge 14.23.2.2617
Enderman Evolution 1.0.9

**Comment by p455w0rd** [comment]
eh..i don't feel like forgetting..i pushed to curse..everyone can deal with it lol
