### ISSUE TITLE
[suggestion] Add journemap icons for evolved endermen and friendermen

### ISSUE THREAD

**Issue by maham** [p455w0rd/EndermanEvolution#15]
Currently journeymap only shows the undefined icon. Why not add a custom icon, journeymap have support for it. I can create a PR if someone provides me with icons. (I'm not a very good artist)

**Comment by p455w0rd** [comment]
I like it..I'll work on this before pushing today's update :)

**Comment by p455w0rd** [comment]
![](http://p455w0rd.net/u/10.12.03-22.02.18.png)

**Comment by maham** [comment]
Woah! Beautiful! I'll look forward to the update.
