### ISSUE TITLE
dimension whitelist/blacklist for ender daisy

### ISSUE THREAD

**Issue by 0Navis0** [p455w0rd/EndermanEvolution#19]
It will prevent ender daisy to spawn in all dimensions it shouldn't spawn.

**Comment by p455w0rd** [comment]
there is a config option:
```
# Whether or not Ender Daisies generate naturally [default: true]
B:EnableEnderDaisyWorldGen=true
```

Use this for now..I will add support for a dim whitelist/blacklist though

**Comment by p455w0rd** [comment]
finally :)

**Comment by p455w0rd** [comment]
i keep em open till I get the jar on curse ;)
