### ISSUE TITLE
[1.12.2 1.0.1 (forge 14.23.1.2582) No item pick up from Frienderman

### ISSUE THREAD

**Issue by VallenFrostweaver** [p455w0rd/EndermanEvolution#2]
Frienderman won't pick up items (once given a chest). I have given it a vanilla chest and dropped items. The chest in it's hands keeps opening and closing but no items are picked up.  It will still attack mobs and follow me but no item pick up. I have to admit though that I don't know how I take the chest back if it did have items in it anyway as that won't work in a normal inventory (having a chest with contents in it) without something like a cardboard box from Mekanism or a Dolly or CHest Transporter. Perhaps I got something wrong here?
![frienderman](https://user-images.githubusercontent.com/13642054/34418883-62f85608-ebf8-11e7-8e00-af88c9dc2882.png)

**Comment by p455w0rd** [comment]
you crouch+right-click to take the chest back..and yes it gives the chest back with contents, you just gotta place it..i'll look into them not picking items up

**Comment by p455w0rd** [comment]
http://p455w0rd.net/u/13.06.50-28.12.17.gif
let me do some more testing

**Comment by VallenFrostweaver** [comment]
Hm. I tried placing, taking, giving. Not sure what the fault is. I have The One Probe, JEI, and Journeymap installed too as a side note.

**Comment by p455w0rd** [comment]
SSP or SMP?

**Comment by xAlicatt** [comment]
SSP here. I get the chest/shulker open/close animation spammed over and over, but no actual pickup seems to happen. There is no console feedback. I attempted using vanilla chest and Iron Chest chests/shulkers with the same results.

I can only assume it's a mod conflict, since it seems like you aren't having the issue per your attached gif.

**Comment by p455w0rd** [comment]
Oh i am experiencing it..but only in an obfuscated environment...still trying to figure out what's going on

**Comment by p455w0rd** [comment]
Trying to get this issue closed before the next update, is this still happening for you guys in 1.0.5?

**Comment by xAlicatt** [comment]
Let me load up my pack and check for you...

**Comment by p455w0rd** [comment]
thank you! I'm doing the same lol - you're always welcome to join real-time discussion on my discord server https://discord.gg/9J7yhUP
