### ISSUE TITLE
[SkyBlock 3 Departed] Evolved enderman snowball server crash

### ISSUE THREAD

**Issue by VallenFrostweaver** [p455w0rd/EndermanEvolution#21]
It would seem that an evolved enderman is interacting with a snowball. When the area is loaded it crashes the server. Pastebin here: https://pastebin.com/VF7c403v

**Comment by p455w0rd** [comment]
i do not know how this is even possible...I can fix it..but this really shouldn't be possible..basically what's happening is the game is saying the snowball that was thrown at an evolved enderman doesn't have a thrower...the snowball just appeared and targeted the enderman all on its own lol...I can add the check and get a fix in though...thx for the report!

**Comment by VallenFrostweaver** [comment]
It was a snow golem if that helps. :3

**Comment by p455w0rd** [comment]
So I fixed this and made it so a snowball being thrown at an Evolved Enderman doesn't cause aggro (since snowballs do no damage)
