### ISSUE TITLE
Add support for IE garden cloche

### ISSUE THREAD

**Issue by portega** [p455w0rd/EndermanEvolution#28]
Would be very nice that it could be automated with the cloche, or Thermal Expansion Phytogenic insolator.
Perhaps that would ignore the light level, but sure it lets config the growth speed and soil type.

**Comment by p455w0rd** [comment]
i do like this idea..we'll have to see as the mechanic is somewhat involved (for example, you can use bonemeanl on the Ender Daisy if it is planted on End Stone, but not on normal grass/dirt)..also speeds are increased on End Stone...I have never used IE myself other than basic energy gen years ago, so I would need to learn how the cloches work...basically same for the Insolator..but I would very much like to add these integrations

**Comment by p455w0rd** [comment]
[a vidya](https://puu.sh/DbKWx/f7b429adf8.webm)
...soon™

**Comment by p455w0rd** [comment]
Only added support for the garden cloche for now..will look into Phytogenic Insolator later
