### ISSUE TITLE
Reliquary Twilight Cloak causes freeze loop when looking at evolved enderman

### ISSUE THREAD

**Issue by CaptPanda** [p455w0rd/EndermanEvolution#31]
Uncertain if this belongs here or if this is an issue with Reliquary mod, but while wearing an active twilight cloak (As a bauble), looking at an evolved enderman causes game/server to freeze by infinite looping.

Mod versions:
Reliquary-1.12.2-1.3.4.780
EndermanEvolution-1.12.2-1.0.15

https://pastebin.com/bTt29rhX

**Comment by p455w0rd** [comment]
It's on my end...I don't really understand why it would do this tbh, but I just checked the event I was firing and it's not cencellable, so there's no reason to fire it. Thanks, I'll get an update out asap!

**Comment by p455w0rd** [comment]
https://minecraft.curseforge.com/projects/enderman-evolution/files/2664931
