### ISSUE TITLE
WAILA info text is not translatable

### ISSUE THREAD

**Issue by Regnander** [p455w0rd/EndermanEvolution#33]
I'm working on a Swedish translation for this mod and just realized that the info text shown in WAILA is hard-coded. Can you add them to `en_us.lang` so they can be translated?

![1](https://user-images.githubusercontent.com/17113053/55690617-2ad2ca00-5994-11e9-92eb-51fb2f3db860.png)

**Comment by p455w0rd** [comment]
Added. I have been meaning to do this anyway. I will wait to push the next update until i receive your PR (and have the other PRs update)
