### ISSUE TITLE
Endermen crashing with something from Twilight Forest

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/EndermanEvolution#37]
A crash is happening between Twilight Forest and this mod, not sure why its happening. 
https://pastebin.com/5ihxEb2s
https://pastebin.com/xXzJEPpG (with mob grinding utils)

Versions:
forge-14.23.5.2838
EndermanEvolution-1.12.2-1.0.29
twilightforest-1.12.2-3.8.689-universal

**Comment by Gr3atsaga** [comment]
I also have received this crash playing Project Ozone 3.  Removing the mod entirely for now until this is fixed, just finished a decent mob farm and the server crashes almost immediately after starting when one of the evolved endermen die.

**Comment by Naheulf** [comment]
Is this issue realy closed ? I see no update that fix this crash with evolved endermens and charm of life. Nor in this repo, nor in https://github.com/TeamTwilight/twilightforest nor in https://github.com/Cazadorsniper/PO3 .

**Comment by Ludi87** [comment]
> Is this issue realy closed ? I see no update that fix this crash with evolved endermens and charm of life. Nor in this repo, nor in https://github.com/TeamTwilight/twilightforest nor in https://github.com/Cazadorsniper/PO3 .

Looks like its fixed [here](https://github.com/TeamTwilight/twilightforest/issues/768) by TF, but not released yet.
