### ISSUE TITLE
Ticking Entity Error with the Evolved Enderman

### ISSUE THREAD

**Issue by FrostCreeper07** [p455w0rd/EndermanEvolution#38]
Whenever I go into my world upon spawn in my game freezes and i'm forced to end the process and every time i do [this](https://pastebin.com/35LrrdfL) is what i get it seems to be caused by the Evolved Enderman i've updated to the latest versions of both your lib mod and the actual mod, i had to remove it because it's in my modpack and other people are going to more then likely get this too, can you please take a look at it

**Comment by jazzpi** [comment]
I think this is the same issue as #37, which was apparently fixed in TeamTwilight/twilightforest#768. Unfortunately, there's no new Twilight Forest release yet, but upgrading to the 3.9.974 Alpha fixes the issue.

**Comment by p455w0rd** [comment]
yeah, this is fixed on their end..you just gotta use their alphas until they upload a new release
