### ISSUE TITLE
Crash after loading the world

### ISSUE THREAD

**Issue by Cazadorsniper** [p455w0rd/EndermanEvolution#42]
The world start laoding in then the game crashed with this: https://pastebin.com/huHZu8fD
Gonna see if it happens again.

**Comment by Cazadorsniper** [comment]
Ok on EndermanEvolution-1.12.2-1.0.32
it crashes the moment I go into JEI.

**Comment by p455w0rd** [comment]
Please update to version 1.0.33

**Comment by Cazadorsniper** [comment]
Didn't crash in JEI and right when I was going to test them a little, Dank Null crashed
