### ISSUE TITLE
Rather strange crash

### ISSUE THREAD

**Issue by brisingraerowing** [p455w0rd/EndermanEvolution#5]
[Crash Log](https://gist.github.com/BrisingrAerowing/e0bbefa870feea9ca6027ce83c9a8b4a)

Got this when starting up a technical pack I am working on. I honestly have no idea as to what caused this, as my main pack (with even more mods) doesn't crash. I'll try to narrow down any mod conflicts.

**Comment by p455w0rd** [comment]
odd indeed, i'll look into it as soon as I am able :)

**Comment by brisingraerowing** [comment]
I updated Forge on my main pack and EE started crashing with the same issue. This looks like either a Forge change or bug.

**Comment by Zer0Lyfe** [comment]
My latest issue explains why this is happening.

**Comment by p455w0rd** [comment]
this issue should be fixed in next update, just trying to wait for someone to test before I push to curse, if you'd like to, please join https://discord.gg/9J7yhUP and I'll ship you my in-dev version to be sure
