### ISSUE TITLE
crashes with Galacticraft (Entity ID is the same)

### ISSUE THREAD

**Issue by Zer0Lyfe** [p455w0rd/EndermanEvolution#7]
the ID of the Evolved Enderman is same could you change it so it doesn't cause problems with galaticraft
https://github.com/micdoodle8/Galacticraft/issues/3144

**Comment by p455w0rd** [comment]
I replied and I'll get this fixed in the next update, thanks for reporting this!

**Comment by p455w0rd** [comment]
if you can drop by my discord relatively shortly, I'll give you a version to test to ensure things are fixed - https://discord.gg/9J7yhUP
